### ISSUE TITLE
Button to confirm appointment in widget should show 'Confirm' instead of 'Pay and confirm'

### ISSUE THREAD

**Issue by wise-cheng** [dayschedule/dayschedule-widget#22]
If the booking resource does not have 'Accept Payment' specified, then the widget's button should show 'Confirm' and not 'Pay and confirm' to avoid confusion.

**Comment by vickyRathee** [comment]
The `Pay and confirm` show only when payment option is enabled, let me know if that's not the case?

**Comment by wise-cheng** [comment]
I did not connect any payment gateway, and did not check 'Collect payment for this service' for the service resource, yet the button says 'Pay and confirm'
![Screenshot 2023-11-16 at 8 42 48 AM](https://github.com/dayschedule/dayschedule-widget/assets/103758790/c1e4bba9-a8f8-4b6d-90e3-b33e0d77709d)
![Screenshot 2023-11-16 at 8 43 14 AM](https://github.com/dayschedule/dayschedule-widget/assets/103758790/0aa76312-48be-4c71-b3ff-08434ee2e5df)
![Screenshot 2023-11-16 at 8 44 39 AM](https://github.com/dayschedule/dayschedule-widget/assets/103758790/c925d0b7-844d-44a5-bc67-fa324096085c)

**Comment by vickyRathee** [comment]
Yes, it’s static in “service” types. Will be fixed this weekend
