### ISSUE TITLE
The popup widget cannot be easily closed on a mobile device, i.e. no 'X' button

### ISSUE THREAD

**Issue by wise-cheng** [dayschedule/dayschedule-widget#23]
I have a slightly edge case.  My app uses a webview in React Native to show the live site.  Upon clicking on the 'Book Now' button, the daySchedule popup will be displayed perfectly.  However, it is difficult to dismiss/close the pop up as there is no close button, to close the popup, I have to click area outside the popup.  Since the daySchedule popup occupies the mobile device screen, there isn't any area to dismiss the popup except the gap between the resource and 'Select a Time' section.  Please see attached screenshot and add a button (or a 'X' in the upper right) to close the popup.

<img width="507" alt="Screenshot 2023-11-15 at 8 34 25 AM" src="https://github.com/dayschedule/dayschedule-widget/assets/103758790/2da809b6-8fbe-4eb5-9559-501300078b20">

**Comment by vickyRathee** [comment]
Clicking outside will also close the modal, but we will make the x icon responsive in next release
