### ISSUE TITLE
Booking an appointment does not respect the schedule configured for the resource

### ISSUE THREAD

**Issue by wise-cheng** [dayschedule/dayschedule-widget#26]
I have the following setup in dayschedule with a single account:
1. `Resource A` and `Resource B`
2. `Schedule 1` and `Schedule 2` with `Schedule 1` being marked as default
3. `Resource A` is configured with `Schedule 1` and `Resource B` is configured with `Schedule 2`

Since each resource is configured with its own schedule, I assume bookings for each resource will have different schedules, however, it seems that both are using the same schedule that has been marked as default, and not with the one that has been configured.

P.S. I have confirmed the resources do have their respective schedule with GET api `/v1/resources`.  I have also tried to use the GET api `/v1/bookings` to see if the bookings have a `schedule_id`, but unfortunately `schedule_id` isn't a field in the response.

**Comment by wfcheng** [comment]
It is my misunderstanding of how to set up default schedules for resources.  I have verified in daySchedule dashboard that the schedules do work as designed, hence this issue should be closed.
