### ISSUE TITLE
Nice Plugin!

### ISSUE THREAD

**Issue by mrdavidrees** [dayschedule/dayschedule-widget#5]
Hi I like your plugin and feel that it works quite well.

I had to use it in an iframe as the css breaks my site style which was a little tricky with react.
I would like to see a slightly improved interface as there isn't enough padding between text elements and you should use better grays such as the [tailwind](https://tailwindcss.com/docs/customizing-colors) grays.
I feel an even three columns would look more appealing than 3 different width columns.

I liked that i could pre-fill the form with the previous inputs from my website.
It would be nice to configure actual times that I am available, rather than the current rules, like instead of 1hr meeting, 30m break before, 5 min break after, i would just provide it a list of time slots. this would help sometimes there is times in the middle of the day where you have regular meetings that need to be blocked out every week.

Love what you're doing and I hope it goes well!

**Comment by vickyRathee** [comment]
@mrdavidrees You can create multiple events and open the url dynamically. 

For example, create 3 events with following `eventUrl` - 

1. /5min
2. /15min
3. /30min

Then open the widget dynamically with selected URL or button click:
```
const mainUrl  = 'https://vikash.dayschedule.com';
daySchedule.initPopupWidget( {  
   url: mainUrl + eventUrl 
});
```

Or you may [add multiple duration options](https://dayschedule.com/docs/t/how-to-specify-custom-durations-on-appointment-scheduling-page/376) in same event as well. 

![multiple meeting durations](https://user-images.githubusercontent.com/6106479/219546666-538da291-71dc-4e38-95dc-31ba8af08432.png)

We will review the tailwind styling in our weekly meeting.
